### ISSUE TITLE
What would be the right way to use other pouchdb plugins alongside this library?

### ISSUE THREAD

**Issue by abhinavzspace** [powet/elm-pouchdb#3]
Hi @powet 

This library is coming out to be very handy while using it in a small personal project. No major blocker yet.

Can you suggest some ways pouchdb plugins like SuperLogin, pouchdb-authentication, pouchdb-find, etc be used alongside this library?

Thanks!

**Comment by eticav** [comment]
Hi @**abhinavzspace**

Thanks for your encouragements. I'll be mainly focusing on stabilizing the core functionalities of pouchdb-elm in the next couple of months, although I have some interest in pouchdb-authentication.

The way to go for any plugins is the Elm standard way, either via ports either via native extension. 
I find writing native extension quite advantageous because your code can be reused more easily by other users whereas with ports you mainly focus on yours immediate needs and makes your quite no really reusable.

If you decide to write a native extension, I would be very be happy to collaborate with you.

**Comment by abhinavzspace** [comment]
Elm is a very interesting language with fast growing ecosystem. But after tinkering with it for a few weeks, I have decided to use react/redux for this particular project since I need rapid development on this thing. I think elm needs a few more months to really take off.

**Comment by eticav** [comment]
Hi  **@abhinavzspace**

I understand your concerns. It's a trade-off between rapid development using tools and an ecosystem that you already master and en emerging technology with lots of promesses but not fully mature yet. 
I made this choice a few months ago myself and wanted to give Elm a chance and I have no regrets.

I'm sure you'll come back very soon to the newly born Elm world.
