### ISSUE TITLE
Not working with elm-reactor

### ISSUE THREAD

**Issue by ramstein74** [powet/elm-pouchdb#6]
Hello i would love to use it but i get this error.
![image](https://cloud.githubusercontent.com/assets/1210858/19384893/cc108278-9203-11e6-8f14-04d164f06ee5.png)
can u help?
thank you

**Comment by eticav** [comment]
Hi @ramstein74,

pouchdb-elm has not yet been reviewed by the Elm team, it is therefore not available as an Elm package. It not very hard to setup though, you should find everything you need in #1 to fix your setup. I'm sorry I have no other solution till the Elm team validates the native modules.

Thanks

**Comment by M-I** [comment]
@ramstein74 was not trying to use elm-pouchdb as an unpublished package (yet), but just trying out the ./example &/or the ./test folder with the `elm-reactor` cmd. I get the same error by doing just that.
The compiled js still refer to the _user$project$Native pattern. 
For example if you run `elm-make example1.elm` the output will have code like 
> var _user$project$Pouchdb$destroy = function (db) {
>        return _user$project$Native_ElmPouchdb.destroy(db);
>};

instead of (I suppose)
> var _user$project$Pouchdb$destroy = function (db) {
        return _powet$elm_pouchdb$Native_ElmPouchdb.destroy(db);
};
 
Reverting to the previous pattern fixes the issue
